### ISSUE TITLE
Linux build process is scuffed

### ISSUE THREAD

**Issue by adamhutchings** [dhs-gamedev/game-2021#23]
The Linux workflow file is pretty cursed and possibly dangerous to run on any real machine - could someone who has managed to compile this on Linux replace [this file](https://github.com/dhs-gamedev/game-2021/blob/main/.github/workflows/linux.yml) with a better build process?

**Comment by Sophon96** [comment]
How?

**Comment by adamhutchings** [comment]
I amend - the Linux build process is broken but still says it passes.
